// Copyright (c) Meta Platforms, Inc. and affiliates.

// __TRITON_AOT_GENERATE_BEGIN__ HEADER_INCLUDE
#include "kernel.h"
// __TRITON_AOT_GENERATE_END__ HEADER_INCLUDE
// These headers are used by code generated at runtime in KERNEL_SPECS blocks
#include <torch/csrc/stable/accelerator.h>
#include <torch/csrc/stable/macros.h> // NOLINT(facebook-unused-include-check)
#include <torch/csrc/stable/tensor.h> // NOLINT(facebook-unused-include-check)
#include <torch/headeronly/core/ScalarType.h> // NOLINT(facebook-unused-include-check)

inline void triton_aot_cu_check(CUresult err, const char* file, int line) {
  if (err != CUDA_SUCCESS) {
    const char* err_str;
    (void)cuGetErrorString(err, &err_str);
    throw std::runtime_error(
        std::string(file) + ":" + std::to_string(line) +
        " CUDA driver error: " + (err_str ? err_str : "unknown"));
  }
}
#define TRITON_AOT_CU_CHECK(EXPR) triton_aot_cu_check(EXPR, __FILE__, __LINE__)

// NOLINTNEXTLINE(facebook-hte-NullableReturn): error path throws
inline cudaStream_t triton_aot_get_current_stream() {
  auto device_idx = torch::stable::accelerator::getCurrentDeviceIndex();
  void* stream_ptr = nullptr;
  // TODO: No torch::stable op provides the same functionality
  // today. Revisit if torch exposes a proper stable::accelerator stream API.
  if (aoti_torch_get_current_cuda_stream(device_idx, &stream_ptr) != 0) {
    throw std::runtime_error("Failed to get current CUDA stream");
  }
  return reinterpret_cast<cudaStream_t>(stream_ptr);
}

namespace triton {
namespace aot {

namespace {
int compute_capability() {
  // Cached: AOTT hosts use homogeneous GPUs.
  static int cc = 0;
  if (cc == 0) {
    CUdevice device;
    TRITON_AOT_CU_CHECK(cuCtxGetDevice(&device));
    int major, minor;
    TRITON_AOT_CU_CHECK(cuDeviceGetAttribute(
        &major, CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MAJOR, device));
    TRITON_AOT_CU_CHECK(cuDeviceGetAttribute(
        &minor, CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MINOR, device));
    cc = major * 10 + minor;
  }
  return cc;
}
} // namespace

namespace {
#ifdef USE_ROCM
void enable_large_smem_or_throw(int shared, hipFunction_t func) {
  // HIP: LDS is fully available by default; no opt-in needed.
  // TODO: investigate -- should we still hard-reject ``shared >
  // hipDeviceAttributeMaxSharedMemoryPerBlock`` here, symmetric with the
  // CUDA branch below? Today AMD AOT-T silently launches and may fail
  // opaquely in hipLaunchKernel.
  return;
}
#else
// Mirrors upstream Triton's NVIDIA driver setup
// (``third-party/triton/.../nvidia/backend/driver.c``) plus an AOT-T-
// specific hard reject for ``shared > shared_optin`` -- the JIT path's
// launch-time ``OutOfResources`` check (``compiler.py::_init_handles``)
// doesn't fire under AOT-T.
void enable_large_smem_or_throw(int shared, CUfunction func) {
  CUdevice device;
  TRITON_AOT_CU_CHECK(cuCtxGetDevice(&device));
  int shared_optin;
  TRITON_AOT_CU_CHECK(cuDeviceGetAttribute(
      &shared_optin,
      CU_DEVICE_ATTRIBUTE_MAX_SHARED_MEMORY_PER_BLOCK_OPTIN,
      device));
  if (shared > shared_optin) {
    throw std::runtime_error(
        "AOT-T kernel needs " + std::to_string(shared) +
        " bytes SMEM but device " + std::to_string(static_cast<int>(device)) +
        " max opt-in is " + std::to_string(shared_optin) + " bytes.");
  }
  if (shared > 49152 && shared_optin > 49152) {
    // >48KB: opt cubin into prefer-shared cache + raise dynamic SMEM cap.
    TRITON_AOT_CU_CHECK(
        cuFuncSetCacheConfig(func, CU_FUNC_CACHE_PREFER_SHARED));
    int shared_static;
    TRITON_AOT_CU_CHECK(cuFuncGetAttribute(
        &shared_static, CU_FUNC_ATTRIBUTE_SHARED_SIZE_BYTES, func));
    TRITON_AOT_CU_CHECK(cuFuncSetAttribute(
        func,
        CU_FUNC_ATTRIBUTE_MAX_DYNAMIC_SHARED_SIZE_BYTES,
        shared_optin - shared_static));
  }
}
#endif
} // namespace

// Hidden for the same reason as the prototypes in kernel.h: one .so per
// forward method, all defining the same `triton::aot::<kernel>` selector, all
// dlopen'd into one predictor process. Only torch_op.cpp calls these, and it
// is compiled into this same .so.
#pragma GCC visibility push(hidden)
// __TRITON_AOT_GENERATE_BEGIN__ KERNEL_SPECS
// __TRITON_AOT_GENERATE_END__ KERNEL_SPECS

// __TRITON_AOT_GENERATE_BEGIN__ SELECTOR
// __TRITON_AOT_GENERATE_END__ SELECTOR
#pragma GCC visibility pop

} // namespace aot
} // namespace triton

// Anchor: keeps the inline `triton_aot_get_current_stream` (and its reference
// to `aoti_torch_get_current_cuda_stream`) from being dead-stripped at
// buck-build time, where KERNEL_SPECS is empty. `weak` dedups the symbol
// across the per-op .so files generated by the runtime template substitution.
extern "C" __attribute__((weak, visibility("default"))) cudaStream_t
__triton_aot_anchor_get_stream() {
  return triton_aot_get_current_stream();
}
